const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const core = require('@actions/core');
const exec = require('@actions/exec');
const github = require('@actions/github');

async function createPr(workspaceDir, repository, sourceBranch, githubToken, githubApiUrl, sourceCodeDir, batchFixResponse = null) {
  try {
    const isSastFix = !!batchFixResponse;
    const fixPrBranchPrefix = isSastFix ? 'sastfix' : 'scafix';
    const fixPrCommitMessage = isSastFix
      ? 'Changes auto-generated by Veracode Fix for SAST'
      : 'Changes auto-generated by Veracode Fix for SCA';

    // Generate current changes diff hash
    core.info('Generating current changes diff...');
    let currentDiff = '';

    await exec.exec('git', ['--no-pager', 'diff', '--no-color', 'HEAD'], {
      cwd: sourceCodeDir,
      listeners: {
        stdout: (data) => {
          currentDiff += data.toString();
        }
      }
    });

    // Create short hash from diff
    const diffHash = crypto.createHash('sha256').update(currentDiff).digest('hex');
    const diffShortHash = diffHash.substring(0, 8);
    core.info(`Current diff short hash: ${diffShortHash}`);

    // Create new branch for Fix Pull Request
    const branchName = `${fixPrBranchPrefix}-${diffShortHash}-${sourceBranch}`;
    core.info(`Creating branch: ${branchName}`);

    await exec.exec('git', ['checkout', '-b', branchName], {
      cwd: sourceCodeDir
    });

    // Configure git user
    await exec.exec('git', ['config', 'user.name', 'Veracode SCA Fix Bot'], {
      cwd: sourceCodeDir
    });

    await exec.exec('git', ['config', 'user.email', 'sca-fix@veracode.com'], {
      cwd: sourceCodeDir
    });

    // Show status
    await exec.exec('git', ['status'], {
      cwd: sourceCodeDir
    });

    // Commit and push changes
    core.info('Committing changes...');
    await exec.exec('git', ['add', '-u'], {
      cwd: sourceCodeDir
    });

    await exec.exec('git', ['commit', '-m', fixPrCommitMessage], {
      cwd: sourceCodeDir
    });

    core.info(`Pushing branch to origin/${branchName}...`);
    await exec.exec('git', ['push', 'origin', branchName], {
      cwd: sourceCodeDir
    });

    // Create Pull Request using GitHub API (Octokit)
    core.info('Creating pull request via GitHub API...');

    let prTitle, prBody;

    if (batchFixResponse) {
      // Dynamic SAST PR title and body from the CLI batch fix response
      prTitle = generateSastPrTitle(batchFixResponse);
      prBody = generateSastPrBody(batchFixResponse);
      core.info('Generated dynamic SAST PR title and body from batch fix response');
    } else {
      // SCA fallback: read sca-fix-report.md
      prTitle = `[Veracode Fix for SCA] ${branchName}`;
      prBody = '';
      const reportPath = path.join(sourceCodeDir, 'sca-fix-report.md');
      if (fs.existsSync(reportPath)) {
        try {
          prBody = fs.readFileSync(reportPath, 'utf8');
          core.info('Loaded sca-fix-report.md for PR description');
        } catch (error) {
          core.warning(`Failed to read sca-fix-report.md: ${error.message}`);
          prBody = '## Veracode Fix for SCA\n\nAutomated dependency updates applied.';
        }
      } else {
        core.warning('sca-fix-report.md not found. Using default PR description.');
        prBody = '## Veracode Fix for SCA\n\nAutomated dependency updates applied.';
      }
    }

    // Parse repository string (format: owner/repo)
    const [owner, repo] = repository.split('/');
    if (!owner || !repo) {
      throw new Error(`Invalid repository format. Expected 'owner/repo', got '${repository}'`);
    }

    // Initialize Octokit client
    const octokit = github.getOctokit(githubToken);

    // Create pull request using Octokit
    const prResponse = await octokit.rest.pulls.create({
      owner,
      repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: sourceBranch
    });

    // Clean up report file after using it
    try {
      if (fs.existsSync(reportPath)) {
        fs.unlinkSync(reportPath);
        core.info('Cleaned up sca-fix-report.md');
      }
    } catch (error) {
      core.warning(`Failed to clean up sca-fix-report.md: ${error.message}`);
    }

    // Save response to file for use in upload-pr-comment step
    const responseFilePath = path.join(workspaceDir, 'github_fix_pr_post_response.json');
    fs.writeFileSync(responseFilePath, JSON.stringify(prResponse.data, null, 2));

    return { success: true, prResponse: prResponse.data };
  } catch (error) {
    throw new Error(`Failed to create pull request: ${error.message}`);
  }
}

/**
 * Build a concise PR title from the batch fix response (v2 schema).
 */
function generateSastPrTitle(batchFixResponse) {
  const s = batchFixResponse?.summary;
  if (s && s.flawsInPatches > 0) {
    return `[Veracode Fix for SAST] ${s.flawsInPatches} finding(s) addressed across ${s.filesTouched} file(s)`;
  }
  return '[Veracode Fix for SAST] Automated security fixes';
}

/**
 * Build a rich markdown PR body from the batch fix response (v2 schema).
 */
function generateSastPrBody(batchFixResponse) {
  if (!batchFixResponse) {
    return '## Veracode Fix for SAST\n\nAutomated security fixes applied.';
  }

  const s = batchFixResponse.summary || {};
  const patches = batchFixResponse.patches || [];
  const flaws = batchFixResponse.flaws || [];

  let body = '## Veracode Fix for SAST\n\n';

  // Summary table
  body += '### Summary\n\n';
  body += '| | Count |\n|---|---|\n';
  body += `| Findings included in patches | **${s.flawsInPatches ?? 0}** |\n`;
  body += `| Patches generated | **${s.patchCount ?? 0}** |\n`;
  body += `| Files modified | **${s.filesTouched ?? 0}** |\n`;
  body += `| Findings not attempted | **${s.flawsNotAttempted ?? 0}** |\n`;
  body += `| Findings with failed attempt | **${s.flawsAttemptFailed ?? 0}** |\n\n`;

  // Patches section
  if (patches.length > 0) {
    body += '### Patches Applied\n\n';
    for (const patch of patches) {
      const fileList = (patch.files || []).map(f => `\`${f.path}\``).join(', ');
      body += `**${patch.patchId}** — ${fileList}\n\n`;
      if (patch.suggestedCommitMessage) {
        body += `> ${patch.suggestedCommitMessage}\n\n`;
      }
      if (patch.explanation) {
        body += `${patch.explanation}\n\n`;
      }
      if (patch.addressesIssueIds && patch.addressesIssueIds.length > 0) {
        body += `Addresses issue IDs: ${patch.addressesIssueIds.join(', ')}\n\n`;
      }
    }
  }

  // Not attempted
  const notAttempted = flaws.filter(f => f.outcome === 'NOT_ATTEMPTED');
  if (notAttempted.length > 0) {
    body += '### Findings Not Attempted\n\n';
    body += '| Issue ID | File | Line | Reason |\n|---|---|---|---|\n';
    for (const f of notAttempted) {
      body += `| ${f.issueId} | \`${f.path}\` | ${f.line} | ${f.message || f.reason || ''} |\n`;
    }
    body += '\n';
  }

  // Failed attempts
  const failed = flaws.filter(f => f.outcome === 'ATTEMPT_FAILED');
  if (failed.length > 0) {
    body += '### Findings With Failed Attempts\n\n';
    body += '| Issue ID | File | Line | Reason |\n|---|---|---|---|\n';
    for (const f of failed) {
      body += `| ${f.issueId} | \`${f.path}\` | ${f.line} | ${f.message || f.reason || ''} |\n`;
    }
    body += '\n';
  }

  body += '> ℹ️ Rescan is recommended to confirm CWE fixes are resolved.\n';
  return body;
}

module.exports = createPr;
